# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=40)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('to_approve', 'To Approve'), ('approved', 'Approved'), ('closed', 'Closed'), ('not_a_bug', 'Not a Bug'), ('wontfix', "Won't fix")], default='to_approve', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
