# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('to_approve', 'To Approve'), ('approved', 'Approved'), ('closed', 'Closed'), ('not_a_bug', 'Not a Bug'), ('wontfix', "Won't fix")], default='to_approve', max_length=10),
        ),
    ]
