# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
