# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_update_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
